### ISSUE TITLE
When entering prompt, it generates error

### ISSUE THREAD

**Issue by hinakhadim** [LangbaseInc/langbase#37]
When I enter the prompt to generate the calculator app, I get this error "Body has already been used. It can only be used once. Use tee() first if you need to read it twice"

https://github.com/user-attachments/assets/d298aa05-0db0-4b45-8820-a0146a925ef4

**Comment by msaaddev** [comment]
@hinakhadim thanks for reporting this! It has been fixed. Can you please try again and see if you run into the issue again?

**Comment by hinakhadim** [comment]
It's working now. Thanks for a quick fix!
